### ISSUE TITLE
Depdency Cycle in CentOS7

### ISSUE THREAD

**Issue by mf-lit** [michaeltchapman/puppet-galera#40]
The module seems to get itself into a dependency cycle when run against centos7:

==> control1: Error: Could not apply complete catalog: Found 1 dependency cycle:
==> control1: (Anchor[mysql::server::start] => Class[Mysql::Server::Install] => Package[mysql-server] => Class[Mysql::Server::Install] => File[/var/run/mariadb] => Class[Galera::Repo] => Class[Mysql::Server] => Anchor[mysql::server::start])

I can't get my head around the various anchors in the init script to figure out why this occurs. What's weird is that this doesn't happen when I test against centos6.

**Comment by michaeltchapman** [comment]
Hello! I had a go at this and have a patch here: https://github.com/michaeltchapman/puppet-galera/pull/41 if you have time to take a look. It's because the repo is -> mysql::server class so that the repo is set prior to the mysql package being installed, and recently the centos 7 support that was added put the mariadb specific directory resources inside the repo class.

**Comment by mf-lit** [comment]
Damn, that was fast!!
I've tested and the fix looks good for me (and thanks for the updated example manifest too).

Thanks so much.
Marc.
