### ISSUE TITLE
nc has no option -z in centos 7

### ISSUE THREAD

**Issue by ylockerman** [michaeltchapman/puppet-galera#48]
Hi,

There seems to be an issue with init.pp on Centos 7. It would appear that nc done not have the -z command on that platform. My workaround is to replace the "onlyif" call for the bootstrap_galera_cluster with:

`"ret=1; for i in ${server_list}; do nc \$i ${wsrep_group_comm_port} < /dev/null; if [ \"\$?\" = \"0\" ]; then ret=0; fi; done; /bin/echo \$ret | /bin/grep 1 -q"`

which seems to work on my system.

**Comment by michaeltchapman** [comment]
You're right, and yet the centos7.pp in examples seems to work for me under vagrant, which is a bit strange. Thanks for pointing this out.

**Comment by mf-lit** [comment]
Hmm, this is spooky. I've been running this module for several weeks without issue, then yesterday I ran puppet against the "$galera_master" and the node went ahead and bootstrapped itself due to exactly this problem. Yikes.

It's  a nasty bug as it left me with three nodes in one cluster and one node in a new cluster. The cluster is frontended by haproxy and this continued to healthcheck all four nodes successfully. The next result was that one in four queries was against a bad database!

ylockerman's workaround looks pretty solid, but does take significantly longer to timeout than 'nc -z'. It may be preferable to use something like tcping?

**Comment by michaeltchapman** [comment]
Yep gonna change it to nmap or tcping I think.

**Comment by ylockerman** [comment]
I looked into using nmap when I was writing my workaround. The issue I ran into is that nmap (and tcping) is not installed by default in Centos. Thus, if you use it, it seems like the package will need to be installed manually.

**Comment by michaeltchapman** [comment]
Requiring packages isn't a big problem as long as they're in the standard repos or epel at least. I think nmap is in the base ones so that's probably better.

**Comment by michaeltchapman** [comment]
@mf-lit you raise a good point as well - the timeouts (and maybe retries) probably need to be configurable so that a second of packet loss doesn't result in a bad bootstrap.

How's this to address the nc issue? 

https://github.com/michaeltchapman/puppet-galera/pull/49
