### ISSUE TITLE
Dependency cycle

### ISSUE THREAD

**Issue by clicktrend** [michaeltchapman/puppet-galera#69]
If I run puppet agent it fails with 

> Error: Failed to apply catalog: Found 1 dependency cycle:
(Exec[clean_up_ubuntu] => Class[Mysql::Server::Config] => File[/etc/mysql/conf.d] => Class[Mysql::Server::Config] => Class[Mysql::Server::Install] => Package[mysql-server] => Exec[clean_up_ubuntu])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz

My configuration is 

```
class { 'galera':
        status_password => $db_cluster['status_password'],
        root_password   => $root_password,
        galera_servers => $db_cluster['nodes'],
        galera_master  => $db_cluster['master'],
        local_ip => $servers[$::fqdn]['ip'],
        vendor_type => 'percona',
        vendor_version => '5.6',
        wsrep_sst_method => 'xtrabackup-v2',
        configure_firewall => false,
        override_options => {
            mysqld => {
                wsrep_cluster_name             => $db_cluster['group_name'],
                wsrep_provider_options         => '"gcache.size=8192M;socket.checksum=1;"',
                skip_name_resolve              => true,
                innodb_flush_method            => 'O_DIRECT',
                innodb_log_files_in_group      => 2,
                innodb_log_file_size           => '64M',
                innodb_flush_log_at_trx_commit => 1,
                innodb_file_per_table          => 1,
                innodb_buffer_pool_size        => '592M',
                tmp_table_size                 => '32M',
                max_heap_table_size            => '32M',
                max_connections                => 500,
                thread_cache_size              => 50,
                open_files_limit               => 65535,
                table_definition_cache         => 4096,
                table_open_cache               => 4096,
                max_allowed_packet             => '16M',
                max_connect_errors             => 1000000,
                key_buffer_size                => '32M',
                log_bin                        => '/var/lib/mysql/mysql-bin',
                expire_logs_days               => 14,
                sync_binlog                    => 1,
                bind_address                   => '0.0.0.0'
            }
        }
    }
```
I'm using the master branch.

**Comment by kqi-sistemi** [comment]
Same error.

**Comment by koma85** [comment]
+1

**Comment by michaeltchapman** [comment]
Hi guys, it works with puppetlabs-mysql 3.7.0, but not 3.8.0. The offending commit is here: https://github.com/puppetlabs/puppetlabs-mysql/commit/8b366fe7df52abf8ed90eea5aafcc3f1c2d70810 and it places config before the package install. After fixing the dependency cycle there is an essentially unfixable problem: on debians, mysql will attempt to start as part of the package install, and due to this patch it is using the galera config instead of the default config, which will fail because the cluster hasn't been bootstrapped, which means the package resource in puppet fails.

We may be able to work around by doing something really hacky, like moving the conf directory back and forth just for the install, but if you want something functional use 3.7.0 for now.

**Comment by clicktrend** [comment]
sorry but downgrading to 3.7.0 still does not work. 3.6.2 is not installing at all.

**Comment by michaeltchapman** [comment]
@clicktrend I fixed the above issue as far as I know, so the latest mysql (3.8.0) should now work. Anything older likely won't, since the dependencies are in a different order.

**Comment by clicktrend** [comment]
@michaeltchapman thanx. I got it work! Your master branch did it :-) 👍
